# Generated by Django 5.1.4 on 2025-02-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
